// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsmtxzftwhjkfvbxescq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zbXR4emZ0d2hqa2Z2Ynhlc2NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTIzMTMsImV4cCI6MjA3MDU2ODMxM30.G1-j8ATXYxV9yVX2wQutk5mISg4gq0v7GpiEno4Cs-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});