// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eshikfzcmectrysbrvbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzaGlrZnpjbWVjdHJ5c2JydmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzkwNTEsImV4cCI6MjA2NDg1NTA1MX0.2obPBVGVuyQsDwm2UgbNZpOW8mx_jXcPR3OIeweopXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);